[package]
name = "rs-uefi-varstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "*"

[lib]
path = "src/lib.rs"
test = true